
defaults:
  - _self_ # to avoid a warning
  - data: mnist 
  - optimizer: default
  - model: basic_mlp
  - logger: wandb
  - pruning: basic
  - corruption: basic
  - trainer: default
  - hydra: default
  - hparams_search: null

seed: null
task_name: "train"
