
defaults:
  - _self_ # to avoid a warning
  - data: mnist 
  - optimizer: hp
  - model: basic_mlp
  - logger: wandb
  - pruning: basic
  - corruption: basic
  - trainer: default
  - trainer/callbacks: early_stopping

hydra:
  sweep:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra:job.num}
  

save_dir: logs/ # for wandb
epochs: 10
seed: null
