
defaults:
  - _self_ # to avoid a warning
  - data: mnist 
  - optimizer: hp
  - model: basic_mlp
  - logger: wandb
  - pruning: basic
  - corruption: basic
  - trainer: default
  - hydra: default
  - hparams_search: mnist_optuna

save_dir: logs/ # for wandb
seed: null
task_name: "train"
