
defaults:
  - _self_ # to avoid a warning
  - task: mnist
  - optimizer: default
  - model: basic_mlp
  - logger: wandb
  - pruning: basic
  - corruption: basic
  - trainer: default
  - trainer/callbacks: early_stopping
  - hydra: default
  - hparams_search: null

save_dir: logs/
seed: null
task_name: "train"
