# @package _global_
defaults:
  - override /hydra/sweeper: optuna  # This will look for conf/hydra/sweeper/optuna.yaml

optimized_metric: "val/val_acc_best"

hydra:
  mode: MULTIRUN

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    n_jobs: 1
    direction: maximize
    n_trials: 2

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html

    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 13
      n_startup_trials: 2 # number of random sampling runs before optimization starts

    params:
      # optimizer.lr: interval(0.0001, 0.1)
      data.batch_size: choice(64, 128)
      # model.net.hidden_size1: choice(64, 128, 256)
      # model.net.hidden_size2: choice(64, 128, 256)
      # model.net.hidden_size3: choice(32, 64, 128, 256)