_target_: src.models.gpt_module.GPT_module
net:
  _target_: src.models.components.nanoGPT.GPT
  config:
    block_size: 120
    vocab_size: ${data.n_tokens}
    n_layer: 2
    n_head: 4
    n_embd: 64
    dropout: 0.0
    bias: True
    causal: False

optimizer: ${optimizer}
