lr: 0.01
weight_decay: 0.0
update_alg: "md"  
block_size: 4
alpha: 0.1
momentum: 0.0
dampening: 0.0
nesterov: false
beta1: 0.9
beta2: 0.999

lr_scheduler: "cosine"  # options: "None", "cosine", "steplr"

# cosine lr scheduler
T_max: ${trainer.max_epochs}
eta_min: 0.0

# steplr lr scheduler
step_size: 30
gamma: 0.1

