# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
# defaults:
#   - override hydra_logging: colorlog
#   - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: outputs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
  dir: outputs/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}
