_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${save_dir}
min_epochs: 1
max_epochs: 5

accelerator: auto
devices: auto
check_val_every_n_epoch: 1
deterministic: False

callbacks: ${trainer.early_stopping}
