_target_: lightning.pytorch.trainer.Trainer

# Uses this to save ckp and logs if no logger is provided
default_root_dir: ${save_dir} 

min_epochs: 1 # prevents early stopping
max_epochs: 15

accelerator: auto
devices: auto

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
